import {mechanismContent} from '../film/mechanisms.js';
import {stageData,getStageState,operationStepsBetween} from './learning.js?v=11';
const $=id=>document.getElementById(id),reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const assets={
 cherry:{image:'./assets/cherry-anatomy.jpg',model:'./assets/cherry-anatomy-v9.glb',alt:'红色成熟咖啡果与细致剖面，显示果肉、羊皮层和内部成对的种子',caption:'剖面旁单独摆出另一粒种子 · 通常两颗相对',cameraOffset:[.75,.5,1],fitScale:1.4},
 washed:{image:'./assets/washed-parchment.jpg',model:'./assets/cherry-anatomy-v9.glb',alt:'去果肉清洗后的湿带壳豆，表面仍保留羊皮层',caption:'水洗后，羊皮层仍在',cameraOffset:[.65,.55,1]},
 dry:{image:'./assets/dry-hulling.jpg',model:'./assets/dry-hulling.glb',alt:'干燥的羊皮壳与脱壳后青绿色的咖啡生豆',caption:'先完成干燥，再去除羊皮层',cameraOffset:[.65,.6,1],fitScale:1.35},
 roast:{image:'./assets/roast.jpg',model:'./assets/roast.glb',alt:'从青绿、转黄到褐色的咖啡豆以及烘焙豆的多孔断面',caption:'颜色、体积和内部结构一起改变',cameraOffset:[.28,.75,1]},
 grind:{image:'./assets/grind-tamp.jpg',model:'./assets/grind-tamp.glb',alt:'锥形磨盘的拆解、咖啡颗粒、装粉手柄与平底压粉器',caption:'磨盘拆解 · 研磨后均匀布粉、水平压实',cameraOffset:[.6,.85,1]},
 espresso:{image:'./assets/espresso.jpg',model:'./assets/espresso.glb',alt:'热水经过粉饼与滤篮，浓缩咖啡流入陶瓷杯的剖面示意',caption:'热水经过粉饼；粉渣留在滤篮里',cameraOffset:[.5,.45,1]},
 steam:{image:'./assets/milk-microfoam.jpg',model:'./assets/milk.glb',alt:'蒸汽棒伸入不锈钢奶缸，平整细腻的牛奶表面可见',caption:'先少量进气，再融合成细腻质地',cameraOffset:[.75,.7,1]},
 pour:{image:'../proof/assets/pour-poster.jpg',video:'../proof/assets/coffee-pour-motion.mp4',model:'../proof/assets/coffee-pour-inspection.glb',alt:'奶缸由高到低注奶，再抬高收细流形成心形的过程短片',caption:'',cameraOffset:[.7,.65,1]},
 finished:{image:'./assets/finished-latte.jpg',model:'./assets/finished.glb',alt:'暖光下完成的心形拿铁、细腻陶瓷杯与咖啡豆',caption:'从这一批果实，到一杯拿铁',cameraOffset:[.6,.9,1]}
};
const values=Object.fromEntries(stageData.map(s=>[s.id,s.control.defaultValue]));let index=0,view='cinema',viewer=null,viewerPromise=null,stageToken=0,operationToken=0,pendingSeek=null,modelRequest=0,readyStage=null,modelTask=null,activePart=null,sequence={mode:'idle',stage:null,target:0},tampPause=null;
const shortTitles=['采收果实','水洗处理','干燥脱壳','烘焙','研磨压粉','萃取浓缩','打奶','拉花','完成'];
const nav=$('chapters');stageData.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.dataset.stage=s.id;b.innerHTML='<span>'+String(i+1).padStart(2,'0')+'</span>'+shortTitles[i];b.onclick=()=>selectStage(i);nav.appendChild(b);});
const video=$('scene-video');
$('skip-link').onclick=e=>{e.preventDefault();$('lesson').focus({preventScroll:true});$('lesson').scrollIntoView({block:'start',behavior:reducedMotion?'auto':'smooth'});};
function current(){return stageData[index];}
function selected(){const s=current();return getStageState(s.id,values[s.id],{espressoYieldG:values.espresso});}
function status(text,progress=null,error=false){$('model-status').textContent=text;$('model-status').hidden=!text;$('model-status-box').hidden=!text;$('model-panel').setAttribute('aria-busy',String(!!text&&!error));$('model-progress').hidden=!text||error;if(Number.isFinite(progress)&&progress!==null)$('model-progress').value=progress;else $('model-progress').removeAttribute('value');$('model-retry').hidden=!error;if(error)readyStage=null;}
async function ensureViewer(){if(!viewerPromise)viewerPromise=import('./viewer.js?v=9').then(m=>m.createObjectViewer($('object-canvas'),status)).then(v=>{viewer=v;v.setProjectionHandler?.(updateAnatomyLabels);return v;}).catch(e=>{viewerPromise=null;throw e;});return viewerPromise;}
function pauseSequence(){if(sequence.mode!=='running'&&sequence.mode!=='loading')return;operationToken++;sequence.mode='paused';renderControls();}
function setView(next){if(!['cinema','model'].includes(next))return;if(next===view&&next==='model'&&readyStage===current().id)return Promise.resolve(true);view=next;if(next!=='model'){pauseSequence();tampPause?.();}for(const name of ['cinema','model']){$(name+'-panel').hidden=name!==next;$('tab-'+name).setAttribute('aria-selected',String(name===next));$('tab-'+name).tabIndex=name===next?0:-1;}if(next!=='cinema')video.pause();if(viewer)viewer.setActive(next==='model');$('media-kind').textContent=next==='model'?'实时三维 · 教学示意':assets[current().id].video?'固定视角 · 可暂停短片':'离线渲染 · 参考画面';updateVisualLabel();$('part-guide').hidden=next!=='model';if(next==='model')return readyStage===current().id?Promise.resolve(true):loadCurrentModel();}
function loadCurrentModel(){const token=stageToken,s=current(),a=assets[s.id];if(modelTask&&modelTask.stageToken===token&&modelTask.id===s.id)return modelTask.promise;const request=++modelRequest;readyStage=null;status('正在准备三维物件…');renderPartGuide();const promise=(async()=>{try{const v=await ensureViewer();if(token!==stageToken||request!==modelRequest)return false;v.setActive(view==='model');const loaded=await v.load(a.model,a);if(!loaded||token!==stageToken||request!==modelRequest)return false;readyStage=s.id;applyVisual(s.id,selected());status('');renderPartGuide();return true;}catch(e){if(token===stageToken&&request===modelRequest)status('三维物件暂时没有加载成功。可以重试，也可以先看参考画面。',null,true);console.error(e);return false;}finally{if(modelTask?.request===request)modelTask=null;}})();modelTask={stageToken:token,id:s.id,request,promise};return promise;}
$('model-retry').onclick=async()=>{if(viewer?.contextLost){viewer.dispose();viewer=null;viewerPromise=null;}modelTask=null;const ready=await loadCurrentModel();if(ready)$('object-canvas').focus({preventScroll:true});};
function mediaStatus(text,error=false){$('media-status').hidden=!text;$('media-status-text').textContent=text;$('media-retry').hidden=!error;}
$('media-retry').onclick=()=>selectStage(index);
function updateVisualLabel(){updateAnatomyLabels();const s=current(),v=selected();$('visual-state-label').textContent=view==='model'?(activePart?'结构近看':'当前操作'):s.id==='pour'?'短片回放':'参考画面';$('visual-state-detail').textContent=view==='model'?(activePart?.label||v.readout):s.id==='pour'?v.readout:'结构与材质样本 · 不随参数变化';$('experiment-mode-label').textContent=s.id==='pour'?'短片回放':s.id==='finished'?'重量比较':'三维操作';}
['cinema','model'].forEach((name,i)=>{const b=$('tab-'+name);b.onclick=()=>setView(name);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const other=i?'cinema':'model';setView(other);$('tab-'+other).focus();}};});
function selectStage(i){if(i<0||i>=stageData.length)return;index=i;stageToken++;operationToken++;modelRequest++;readyStage=null;modelTask=null;activePart=null;sequence={mode:'idle',stage:null,target:0};tampPause=null;viewer?.cancelLoad?.();video.pause();const s=current(),a=assets[s.id];$('stage-kicker').textContent=s.kicker;$('stage-title').textContent=s.title;$('mobile-stage-title').textContent=s.title;$('stage-summary').textContent=s.explanation;$('stage-takeaway').textContent=s.summary;$('experiment-heading').textContent=s.question;$('stage-explanation').innerHTML=mechanismContent(s.id).html;$('learning-note').textContent=s.control.contextLabel||'';$('stage-sources').replaceChildren(...s.sourceLinks.map(source=>{const link=document.createElement('a');link.href=source.url;link.textContent=source.title;link.target='_blank';link.rel='noopener';return link;}));$('progress-text').textContent=String(i+1).padStart(2,'0')+' / 09';$('previous').disabled=i===0;$('next').textContent=i===8?'再走一遍':'下一站';nav.querySelectorAll('button').forEach((b,j)=>{if(i===j)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});nav.children[i]?.scrollIntoView({block:'nearest',inline:'nearest',behavior:reducedMotion?'auto':'smooth'});const img=$('scene-image'),imageToken=stageToken;img.classList.add('scene-image-pending');mediaStatus('正在载入画面…');img.onload=()=>{if(imageToken!==stageToken)return;img.classList.remove('scene-image-pending');mediaStatus('');if(typeof Image!=='undefined'&&assets[stageData[index+1]?.id]){const preload=new Image();preload.src=assets[stageData[index+1].id].image;}};img.onerror=()=>{if(imageToken===stageToken)mediaStatus('画面暂时没有加载成功，重试或切换到旋转探索。',true);};img.src=a.image;img.alt=a.alt;img.hidden=!!a.video;if(img.complete&&img.naturalWidth>0)img.onload();video.hidden=!a.video;video.poster=a.image;if(a.video){mediaStatus('');if(video.getAttribute('src')!==a.video){video.src=a.video;video.load();}pendingSeek=values.pour/100*6;seekVideo();}else{video.removeAttribute('src');video.load();}$('cinema-label').textContent=a.caption;$('media-boundary').textContent=s.id==='cherry'?'结构观察窗与薄层厚度经过夸张，以便区分。果胶是湿黏组织，银皮紧贴豆体；观察窗不代表制作时把种子切开。':s.id==='pour'?'固定视角短片可暂停、拖动进度；旋转探索展示独立的定格模型。奶流和拉花是加速的教学视觉近似。':'过程画面为离线渲染；旋转探索可自由转动与拆解，光照与细节有所简化。操作变化用于教学，不是精密仿真。';renderControls();updateFeedback();setView('cinema');history.replaceState(null,'','#'+s.id);}
function renderControls(){const s=current(),c=s.control,host=$('experiment-controls'),focused=host.contains(document.activeElement),focusId=document.activeElement?.id,focusValue=document.activeElement?.dataset?.value;host.replaceChildren();const label=document.createElement('label');label.className='control-label';label.htmlFor='stage-control';label.append(document.createTextNode(c.label));const out=document.createElement('output');out.id='control-readout';label.append(out);host.append(label);if(c.type==='range'){const input=document.createElement('input');input.type='range';input.id='stage-control';input.min=c.min;input.max=c.max;input.step=c.step;input.value=values[s.id];input.setAttribute('aria-label',c.label);input.oninput=()=>changeValue(Number(input.value),true);host.append(input);const ends=document.createElement('div');ends.className='range-ends';c.ends.forEach(text=>{const span=document.createElement('span');span.textContent=text;ends.append(span);});host.append(ends);}else{const options=document.createElement('div');options.className='option-group';options.setAttribute('role','group');options.setAttribute('aria-label',c.label);c.options.forEach(option=>{const b=document.createElement('button');b.type='button';b.textContent=option.label;b.dataset.value=String(option.value);b.setAttribute('aria-pressed',String(option.value===values[s.id]));if(s.id==='dry'&&option.value===2&&values.dry===0){b.disabled=true;b.title='先完成带壳干燥，才能脱壳';}b.onclick=()=>changeValue(option.value);options.append(b);});host.append(options);if(s.id==='dry'&&values.dry===0){const hint=document.createElement('p');hint.className='control-warning';hint.textContent='先选择“带壳干燥完成”，脱壳才会解锁。';host.append(hint);}if(['washed','dry','roast'].includes(s.id)){const play=document.createElement('button');play.className='text-button small';play.textContent=sequence.stage===s.id&&sequence.mode==='paused'?'继续演示':sequence.stage===s.id&&sequence.mode==='running'?'暂停演示':sequence.stage===s.id&&sequence.mode==='loading'?'正在准备…':sequence.stage===s.id&&sequence.mode==='completed'?'重播流程':'依次演示';play.id='sequence-play';play.onclick=()=>sequence.mode==='running'||sequence.mode==='loading'?pauseSequence():autoSequence();host.append(play);}}
 if(s.id==='grind'){const tamp=document.createElement('button');tamp.id='tamp-play';tamp.className='text-button small';tamp.textContent='演示水平压粉';tamp.onclick=()=>playTamp();host.append(tamp);}
 updateControlReadout();if(focused){const replacement=focusId?$(focusId):[...host.querySelectorAll('button')].find(b=>b.dataset.value===focusValue);replacement?.focus({preventScroll:true});}}
function updateControlReadout(){const s=current(),c=s.control;$('control-readout').textContent=c.type==='range'?values[s.id]+(c.unit?' '+c.unit:s.id==='cherry'||s.id==='pour'?'%':''):'';}
async function runSequence(target,from,includeStart=true){const s=current(),token=++operationToken;sequence={mode:'loading',stage:s.id,target,replay:target<from};renderControls();const ready=await setView('model');if(!ready||token!==operationToken||s!==current()){if(token===operationToken){sequence.mode='paused';renderControls();}return;}sequence.mode='running';const steps=operationStepsBetween(s.id,from,target);if(!includeStart)steps.shift();for(const step of steps){if(token!==operationToken||s!==current())return;values[s.id]=step;renderControls();updateFeedback();applyVisual(s.id,selected());await new Promise(r=>setTimeout(r,reducedMotion?1000:1500));}if(token===operationToken){sequence.mode='completed';renderControls();}}
async function autoSequence(){const s=current(),resume=sequence.stage===s.id&&sequence.mode==='paused';return runSequence(resume?sequence.target:s.control.options.length-1,resume?Number(values[s.id]):0,true);}
async function changeValue(value,continuous=false){const s=current(),from=values[s.id];operationToken++;tampPause=null;if(activePart)viewer?.resetCamera();activePart=null;sequence={mode:'idle',stage:null,target:0};if(s.id==='dry'&&Number(value)===2&&Number(from)===0)return;if(['washed','roast'].includes(s.id)&&!continuous&&Math.abs(Number(value)-Number(from))>1)return runSequence(Number(value),Number(from),false);values[s.id]=value;if(['washed','dry','roast'].includes(s.id))$('learning-note').textContent=Number(value)<Number(from)?'回看之前的处理状态。真实处理不会因为回看而逆转。':s.control.contextLabel||'';if(!continuous)renderControls();else updateControlReadout();updateFeedback();if(s.id==='pour'){setView('cinema');video.pause();pendingSeek=Number(value)/100*6;seekVideo();}else if(s.id==='finished'){if(view==='model'&&readyStage===s.id)applyVisual(s.id,selected());}else{if(view!=='model')setView('model');else if(readyStage===s.id)applyVisual(s.id,selected());}}
function metric(label,value,unit=''){const el=document.createElement('div');el.className='metric';const strong=document.createElement('strong');strong.textContent=value;if(unit){const small=document.createElement('small');small.textContent=unit;strong.append(small);}el.append(strong,document.createTextNode(label));return el;}
function updateFeedback(){const s=current(),v=selected();updateVisualLabel();renderPartGuide();if($('experiment-result').textContent!==v.readout)$('experiment-result').textContent=v.readout;const m=$('experiment-metrics');m.replaceChildren();if(s.id==='espresso')m.append(metric('干咖啡粉',18,'g'),metric('杯中浓缩液',v.yieldG,'g'),metric('粉液比',v.ratioLabel));if(s.id==='grind')m.append(metric('固定粉量',18,'g'),metric('流动趋势',v.readout));if(s.id==='finished'){m.append(metric('整杯饮液',v.totalG,'g'),metric('浓缩饮液重量占比',v.espressoBeverageSharePercent,'%'));const bar=document.createElement('div');bar.className='composition-bar';bar.setAttribute('role','img');bar.setAttribute('aria-label',v.shareLabel+'，其余是牛奶');const espresso=document.createElement('span'),milk=document.createElement('span');espresso.style.width=v.espressoBeverageSharePercent+'%';milk.style.width=(100-v.espressoBeverageSharePercent)+'%';bar.append(espresso,milk);m.append(bar);$('learning-note').textContent='成品画面是同一参考杯；这里仅计算饮液重量关系，不改变已成形的拉花，也不预测甜度或咖啡浓度。';}if(s.id==='roast')$('learning-note').textContent='旁边的切开豆是内部结构样本，不代表一爆时豆子会裂成两半。颜色与体积变化为示意。';if(s.id==='steam')$('learning-note').textContent='比较从冷奶重新开始的三种处理。这里切换的是质地与蒸汽棒位置示意；不会修复已经打坏的一壶奶。';}
function seekVideo(){if(pendingSeek===null||!Number.isFinite(video.duration))return;video.currentTime=Math.min(pendingSeek,Math.max(0,video.duration-.001));pendingSeek=null;}
video.addEventListener('error',()=>{if(current().id==='pour')mediaStatus('短片暂时无法播放。请重试，或切换到旋转探索。',true);});video.addEventListener('canplay',()=>{if(current().id==='pour')mediaStatus('');});video.addEventListener('loadedmetadata',seekVideo);video.addEventListener('timeupdate',()=>{if(current().id!=='pour')return;values.pour=Math.min(100,Math.round(video.currentTime/6*100));const c=$('stage-control');if(c)c.value=values.pour;updateControlReadout();updateFeedback();});
video.addEventListener('ended',()=>{if(current().id==='pour'){values.pour=100;const c=$('stage-control');if(c)c.value=100;updateControlReadout();updateFeedback();}});
$('previous').onclick=()=>selectStage(index-1);$('next').onclick=()=>selectStage(index===8?0:index+1);$('restart').onclick=()=>selectStage(0);$('reset-experiment').onclick=()=>{operationToken++;sequence={mode:'idle',stage:null,target:0};activePart=null;tampPause=null;values[current().id]=current().control.defaultValue;renderControls();updateFeedback();if(current().id==='pour'){video.pause();pendingSeek=0;seekVideo();}if(viewer&&view==='model')applyVisual(current().id,selected());};$('reset-camera').onclick=()=>{activePart=null;viewer?.resetCamera();updateVisualLabel();renderPartGuide();};$('top-camera').onclick=()=>viewer?.top();$('zoom-in').onclick=()=>viewer?.zoom(.85);$('zoom-out').onclick=()=>viewer?.zoom(1.18);
function applyVisual(id,v){if(!viewer||readyStage!==id)return;viewer.resetParts();const each=viewer.each;
 if(['cherry','washed','dry'].includes(id)){
  const move=(pattern,amount)=>each(n=>pattern.test(n),(o,original)=>{o.position.y=original.position.y+(o.name.endsWith('_A')?1:-1)*amount;});
  if(id==='cherry'){move(/^Skin_/,v.visualSkinSeparation01*.011);move(/^Pulp_/,v.visualPulpSeparation01*.007);move(/^(Mucilage_|Parchment_|Silverskin_|Seed_)/,v.visualParchmentSeparation01*.0015);each(n=>n==='Calyx',o=>{o.position.y+=v.visualSkinSeparation01*.011;});}
  if(id==='washed'){each(n=>/^(Skin_|Pulp_|Calyx)/.test(n),o=>o.visible=v.step===0);each(n=>/^Mucilage_/.test(n),o=>{o.visible=v.step<3;if(v.step===2)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{m.transparent=true;m.opacity=.23;m.needsUpdate=true;});});}
  if(id==='dry'){if(v.step===0)each(n=>/^Dried_Parchment_/.test(n),o=>(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{m.roughness=.35;m.color.multiplyScalar(1.08);}));if(v.step===2)move(/^Dried_Parchment_/, .0045);}
 }else if(id==='roast'){
  const focus=v.step===0?'GreenBean':v.step===1?'YellowBean':'RoastedBean';each(n=>/Bean|RoastFragment/.test(n),(o,original)=>{const on=focus==='Fractured'?/^Fractured|RoastFragment/.test(o.name):o.name===focus;if(!on)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{m.transparent=true;m.opacity=.24;m.needsUpdate=true;});else o.scale.copy(original.scale).multiplyScalar(v.step<2?1:v.visualBeanScale/1.06);});
 }else if(id==='grind'){
  each(n=>/^GroundParticle/.test(n),(o,original)=>o.scale.copy(original.scale).multiplyScalar(v.visualParticleScale));each(n=>n==='OuterRing_CutawayBurr',(o,original)=>o.position.y=original.position.y+(v.variant==='coarser'?.005:v.variant==='finer'?-.005:0));$('learning-note').textContent=v.assumption+'。磨盘间隙与颗粒变化为放大的结构示意。';
 }else if(id==='espresso'){
  const delta=(v.visualFill01-2/3)*.015,height=.042+delta,innerRadius=height<=.044?.0288+(height-.032)*.125:.0303+(height-.044)*.1,radiusScale=(innerRadius-.0001)/.030;each(n=>n==='Espresso_CremaSurface'||/^Crema_ImpactRipple/.test(n),o=>{o.position.y+=delta;if(nSafe(o)==='Espresso_CremaSurface'){o.scale.x*=radiusScale;o.scale.z*=radiusScale;}});each(n=>n==='Espresso_AmberStream',o=>{const span=.099-.0425;o.scale.y=(span-delta)/span;o.position.y=.099*(1-o.scale.y);});$('learning-note').textContent='18 g 是干粉，杯中读数是浓缩液质量。液面高度只做视觉示意，不是重量到体积的精密换算。';
 }else if(id==='steam'){
  const active=v.variant==='little-air'?'milk_cold_surface':v.variant==='extra-air'?'milk_aeration_surface':'milk_microfoam_surface';viewer.eachNode(n=>/^milk_(cold|aeration|microfoam)_/.test(n),(o)=>{o.scale.set(1,1,1);o.visible=o.name===active||(v.variant==='extra-air'&&o.name==='milk_aeration_bubbles');});viewer.eachNode(n=>n==='steam_wand',(o,original)=>o.position.y=original.position.y+(v.variant==='extra-air'?.007:v.variant==='little-air'?-.004:0));
 }
}
async function playTamp(){const token=++operationToken;const ready=await setView('model');if(!ready||token!==operationToken||current().id!=='grind'||!viewer)return;let progress=0,last=performance.now(),paused=false;tampPause=()=>{paused=true;const button=$('tamp-play');if(button)button.textContent='继续压粉';};const b=$('tamp-play');if(!b)return;b.textContent='暂停压粉';b.onclick=async()=>{if(view!=='model')await setView('model');paused=!paused;b.textContent=paused?'继续压粉':'暂停压粉';};function step(now){if(token!==operationToken||current().id!=='grind')return;const dt=Math.min(.06,(now-last)/1000);last=now;if(!paused)progress+=dt/2.8;const t=Math.min(1,progress),down=t<.4?t/.4:t<.6?1:(1-t)/.4,eased=down*down*(3-2*down);viewer.eachNode(n=>n==='Tamper',(o,original)=>o.position.y=original.position.y-.0445*eased);if(t<1)requestAnimationFrame(step);else{tampPause=null;b.textContent='重播水平压粉';b.onclick=()=>playTamp();updateFeedback();}}if(reducedMotion){viewer.eachNode(n=>n==='Tamper',(o,original)=>o.position.y=original.position.y-.0445);b.textContent='查看压粉接触位置';b.onclick=()=>playTamp();}else requestAnimationFrame(step);$('experiment-result').textContent='保持压粉器水平，让粉床表面平整；这一步不改变已选择的研磨粗细。';}
function nSafe(o){return o.name;}
const partDefinitions={
 cherry:[['skin','果皮',/^Skin_/,'果实外表皮；这里只把切开的两半向外移开，方便观察。'],['pulp','果肉',/^Pulp_/,'柔软的中果皮。内侧黏稠部分称为果胶层，并非又一层硬壳。'],['mucilage','果胶层',/^Mucilage_/,'中果皮内侧的湿黏部分，贴在羊皮层外；不是硬片，也不是纯化学果胶。'],['parchment','羊皮层',/^Parchment_/,'每颗种子各自包着的一层薄内果皮；水洗后仍保留，干燥后才脱壳。'],['silver','银皮',/^Silverskin_/,'紧贴豆体的极薄膜，与羊皮层不同。这里加强薄膜边缘以便观察，不再把它拆成厚白壳。'],['seed','咖啡豆 / 种子',/^Seed_/,'通常两颗种子，较平的侧面相对。豆体主要是胚乳，内部的小胚未单独显示。']],
 washed:[['outer','果皮与果肉',/^(Skin_|Pulp_)/,'去果肉后，它们不再和种子一起进入后续水洗。'],['mucilage','残留果胶',/^Mucilage_/,'去果肉不等于洗净；还要让黏附果胶易于去除，再清洗。'],['parchment','保留的羊皮层',/^Parchment_/,'水洗之后保留羊皮层，下一站带壳干燥。']],
 dry:[['parchment','羊皮壳',/^Dried_Parchment_/,'这层外壳在干燥完成后才去除。'],['seed','生豆',/^Green_Seed$/,'脱壳得到的青绿色种子仍未烘焙。']],
 roast:[['green','青绿生豆',/^GreenBean$/,'烘焙开始前的种子。'],['yellow','转黄阶段',/^YellowBean$/,'受热失水后，颜色开始转黄。'],['roasted','褐色熟豆',/^RoastedBean$/,'体积、裂隙与内部结构一起改变，不能只凭颜色判断风味。'],['section','内部结构样本',/^FracturedBean/,'这是额外剖开的结构样本，不代表一爆会让豆子裂成两半。']],
 grind:[['burr','锥形磨盘',/Burr|CuttingBurr/,'内外磨盘之间的间隙帮助控制颗粒粗细；当前是拆解姿态。'],['grounds','咖啡颗粒',/^GroundParticle/,'这里把颗粒差异适当放大，便于比较。'],['basket','滤篮与粉床',/^(Basket|PreparedCoffeeBed)/,'均匀布粉后，用水平压粉器整理粉床。'],['tamper','压粉器',/^Tamper_/,'平底接触粉床，可用下方的压粉演示观察动作。']],
 espresso:[['water','热水路径',/^Water/,'上方热水通过粉层。蓝白色路径只是流向示意。'],['puck','咖啡粉饼',/^CoffeePuck/,'可溶物进入杯中，粉渣留在滤篮里。'],['stream','浓缩与杯面',/^Espresso_(AmberStream|CremaSurface)/,'杯中重量是浓缩饮液的质量，不是机器注水量。']],
 steam:[['pitcher','奶缸',/450|pitcher|Pitcher/,'薄壁、壶嘴和手柄帮助控制握持与倾倒。'],['wand','蒸汽棒',/steam_wand|Steam_Wand|wand_/,'棒尖靠近液面时进气，稍深后让奶液旋转融合。'],['surface','当前奶泡表面',/^milk_/,'这里比较典型质地，不能仅凭外观推断实际温度。']],
 pour:[['pitcher','奶缸与缸嘴',/450|pitcher|Pitcher|Rolled|ribbon/,'这是倒奶过程的定格姿态。动作请看短片回放。'],['surface','杯面拉花',/Latte|microfoam|meniscus/,'白色图案形成于表面，整杯牛奶与咖啡已经混合。']],
 finished:[['cup','陶瓷杯',/^finished_cup/,'杯壁和手柄有真实厚度，可自由转动近看。'],['surface','拿铁表面',/^finished_latte_surface|^finished_coffee_meniscus/,'拉花是注奶留下的表面图案。'],['beans','咖啡豆',/^finished_roasted_bean/,'杯旁保留熟豆，回看这杯咖啡的原料变化。']]
};
function renderPartGuide(){const s=current(),definitions=partDefinitions[s.id]||[],host=$('part-buttons'),focusedKey=host.contains(document.activeElement)?document.activeElement?.dataset?.part:null;host.replaceChildren();definitions.forEach(([key,label,test,description])=>{const spec={key,label,test,description},button=document.createElement('button');button.type='button';button.dataset.part=key;button.textContent=label;button.setAttribute('aria-pressed',String(activePart?.key===key));button.disabled=readyStage!==s.id||(s.id==='washed'&&((key==='outer'&&values.washed>0)||(key==='mucilage'&&values.washed===3)||(key==='parchment'&&values.washed===0)))||(s.id==='dry'&&key==='seed'&&values.dry<2);button.onclick=()=>focusPart(spec);host.append(button);});$('part-description').textContent=activePart?.description||'选一个名称近看；这是结构观察，不会替你完成处理步骤。';$('part-guide').hidden=view!=='model';if(focusedKey)[...host.querySelectorAll('button')].find(b=>b.dataset.part===focusedKey)?.focus({preventScroll:true});}
async function focusPart(spec){pauseSequence();tampPause?.();const s=current(),token=stageToken;const ready=await setView('model');if(!ready||token!==stageToken)return;if(s.id==='cherry'&&spec.key!=='skin'&&values.cherry<100){values.cherry=100;renderControls();updateFeedback();}applyVisual(s.id,selected());activePart=spec;const matches=(name,object)=>{for(let node=object;node;node=node.parent)if(spec.test.test(node.name))return true;return false;};viewer.each(matches,o=>(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{if(!(s.id==='cherry'&&['mucilage','silver'].includes(spec.key))){m.opacity=1;m.transparent=false;m.needsUpdate=true;}}));const found=viewer.focusParts(matches);renderPartGuide();updateVisualLabel();if(!found)$('part-description').textContent='这一部分在当前步骤不可见。可以先推进对应处理步骤。';}
$('part-reset').onclick=()=>{activePart=null;applyVisual(current().id,selected());viewer?.resetCamera();renderPartGuide();updateVisualLabel();};
const anatomyLabels=[['skin','果皮','外表皮','left',.13,/^Skin_/],['pulp','果肉','柔软组织','left',.39,/^Pulp_/],['mucilage','果胶层','湿黏，非硬壳','left',.65,/^Mucilage_/],['parchment','羊皮层','每颗种子的薄壳','right',.13,/^Parchment_/],['silver','银皮','紧贴豆体的薄膜','right',.39,/^Silverskin_/],['seed','咖啡豆 / 种子','通常两颗','right',.65,/^Seed_/]];
function updateAnatomyLabels(){const host=$('anatomy-labels');if(!host)return;const on=view==='model'&&current().id==='cherry'&&readyStage==='cherry';host.hidden=!on;if(!on||!viewer?.projectPart)return;const rect=$('object-canvas').parentElement.getBoundingClientRect(),w=rect.width,h=rect.height,lw=w<500?88:124;const svg=$('anatomy-leaders');svg.setAttribute('viewBox','0 0 '+w+' '+h);for(const[key,label,detail,side,fraction,pattern]of anatomyLabels){const b=$('anatomy-'+key),line=$('anatomy-line-'+key),point=viewer.projectPart(name=>pattern.test(name)),shown=point?.visible&&point.x>=0&&point.x<=1&&point.y>=0&&point.y<=1&&(values.cherry>=25||key==='skin');b.hidden=!shown;line.style.display=shown?'':'none';if(!shown)continue;const left=side==='left'?10:w-lw-10,top=Math.max(18,Math.min(h-90,h*fraction-20)),endX=point.x*w,endY=point.y*h,startX=side==='left'?left+lw:left,startY=top+20;b.style.left=left+'px';b.style.top=top+'px';b.style.width=lw+'px';b.setAttribute('aria-pressed',String(activePart?.key===key));line.setAttribute('d','M '+startX+' '+startY+' L '+(startX+(side==='left'?9:-9))+' '+startY+' L '+endX+' '+endY);}}
for(const[key]of anatomyLabels){$('anatomy-'+key).onclick=()=>{const d=partDefinitions.cherry.find(x=>x[0]===key);focusPart({key:d[0],label:d[1],test:d[2],description:d[3]});};}

const phoneLayout=matchMedia('(max-width: 760px)');
function placeExperiment(){const experiment=$('experiment-panel'),focused=experiment.contains(document.activeElement)?document.activeElement:null;if(phoneLayout.matches)$('mobile-experiment-mount').append(experiment);else $('desktop-experiment-anchor').after(experiment);focused?.focus({preventScroll:true});}
phoneLayout.addEventListener?.('change',placeExperiment);placeExperiment();

window.addEventListener('pagehide',event=>{pauseSequence();tampPause?.();video.pause();viewer?.setActive(false);if(!event.persisted)viewer?.dispose();});
window.addEventListener('pageshow',event=>{if(event.persisted)viewer?.setActive(view==='model');});

const start=stageData.findIndex(s=>s.id===location.hash.slice(1));selectStage(start<0?0:start);
const inspection=new URLSearchParams(location.search);
if(inspection.get('inspect')==='1'){const c=current().control,raw=inspection.get('value');if(raw!==null){const v=c.type==='range'?Number(raw):c.options.find(o=>String(o.value)===raw)?.value;if((c.type==='range'&&Number.isFinite(v)&&v>=c.min&&v<=c.max)||(c.type!=='range'&&v!==undefined)){values[current().id]=v;renderControls();updateFeedback();}}setView('model');}
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'explore_coffee_journey',description:'Select an educational stage and optionally change its experiment control or viewing mode.',inputSchema:{type:'object',properties:{stage:{type:'string',enum:stageData.map(s=>s.id)},view:{type:'string',enum:['cinema','model']},value:{anyOf:[{type:'number'},{type:'string'}]}},required:['stage'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){const i=stageData.findIndex(s=>s.id===input.stage);if(i<0)throw new Error('Unknown stage');selectStage(i);if(input.value!==undefined){const c=current().control;if(c.type==='range'){if(typeof input.value!=='number'||input.value<c.min||input.value>c.max)throw new Error('Value out of range');}else if(!c.options.some(o=>o.value===input.value))throw new Error('Unknown control choice');await changeValue(input.value);}if(input.view)await setView(input.view);return{stage:current().id,view,feedback:selected().readout};}});}catch{}}
