import * as THREE from 'three';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {GLTFLoader} from '../vendor/loaders/GLTFLoader.js';
import {HDRLoader} from '../vendor/loaders/HDRLoader.js';
export async function createObjectViewer(canvas,onStatus){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});
 renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.8));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(37,1,.00005,100),controls=new OrbitControls(camera,canvas);
 controls.enableDamping=true;controls.dampingFactor=.075;controls.enablePan=false;controls.minPolarAngle=.02;controls.maxPolarAngle=Math.PI*.85;controls.rotateSpeed=.7;
 scene.add(new THREE.HemisphereLight('#eee9d9','#303527',.65));
 const key=new THREE.DirectionalLight('#ffe2bc',1.8);key.position.set(-2,4,3);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key,key.target);
 const fill=new THREE.DirectionalLight('#c6d8f0',.6);fill.position.set(3,2,-3);scene.add(fill);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.ShadowMaterial({color:'#090a08',opacity:.3}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
 let active=false,destroyed=false,contextLost=false,needsRender=true,model=null,loadedPath='',loadToken=0,radius=.2,frameScale=1,environment=null,rafId=null,projectionHandler=null;
 let target=new THREE.Vector3(),defaultOffset=new THREE.Vector3(.65,.55,1);
 const loader=new GLTFLoader(),original=new WeakMap();
 // The environment and object download overlap; a failed environment retains studio lighting.
 new HDRLoader().loadAsync('../proof/assets/comfy-cafe-1k.hdr').then(hdr=>{if(destroyed){hdr.dispose();return;}const pmrem=new THREE.PMREMGenerator(renderer);environment=pmrem.fromEquirectangular(hdr);scene.environment=environment.texture;hdr.dispose();pmrem.dispose();needsRender=true;}).catch(e=>console.warn('Environment unavailable; studio lights remain',e));
 function disposeModel(root){if(!root)return;const geometries=new Set(),materials=new Set(),textures=new Set();root.traverse(o=>{if(!o.isMesh)return;geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const k of ['map','normalMap','roughnessMap','metalnessMap','aoMap','emissiveMap','alphaMap','transmissionMap','clearcoatMap','clearcoatNormalMap'])if(m[k])textures.add(m[k]);}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());}
 function remember(root){root.traverse(o=>{const base={position:o.position.clone(),rotation:o.rotation.clone(),scale:o.scale.clone(),visible:o.visible,materials:[]};if(o.isMesh){const source=Array.isArray(o.material)?o.material:[o.material],materials=source.map(m=>{const copy=m.clone();copy.envMapIntensity=.85;copy.side=THREE.DoubleSide;return copy;});o.material=Array.isArray(o.material)?materials:materials[0];o.castShadow=materials.every(m=>m.opacity>.85);o.receiveShadow=true;base.materials=materials.map(m=>({color:m.color?.clone(),opacity:m.opacity,transparent:m.transparent,roughness:m.roughness}));}original.set(o,base);});}
 function resetParts(){if(!model)return;model.traverse(o=>{const v=original.get(o);if(!v)return;o.position.copy(v.position);o.rotation.copy(v.rotation);o.scale.copy(v.scale);o.visible=v.visible;if(!o.isMesh)return;(Array.isArray(o.material)?o.material:[o.material]).forEach((m,i)=>{const saved=v.materials[i];if(m.color&&saved.color)m.color.copy(saved.color);m.opacity=saved.opacity;if(m.transparent!==saved.transparent)m.needsUpdate=true;m.transparent=saved.transparent;m.roughness=saved.roughness;});});needsRender=true;}
 function each(test,fn){if(model)model.traverse(o=>{if(o.isMesh&&test(o.name,o))fn(o,original.get(o));});needsRender=true;}
 function eachNode(test,fn){if(model)model.traverse(o=>{if(test(o.name,o))fn(o,original.get(o));});needsRender=true;}
 function fit(){const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3());target=box.getCenter(new THREE.Vector3());radius=Math.max(size.x,size.y,size.z,.001)*.63*frameScale;controls.minDistance=radius*.75;controls.maxDistance=radius*8;ground.position.y=box.min.y-radius*.001;Object.assign(key.shadow.camera,{left:-radius*2,right:radius*2,top:radius*2,bottom:-radius*2,near:.0001,far:radius*20});key.position.copy(target).add(new THREE.Vector3(-radius*3,radius*6,radius*4));key.target.position.copy(target);key.shadow.bias=-.00001;key.shadow.normalBias=radius*.003;key.shadow.camera.updateProjectionMatrix();camera.near=radius/1000;camera.far=radius*40;camera.updateProjectionMatrix();resetCamera();}
 function resetCamera(){controls.minDistance=radius*.75;camera.position.copy(target).add(defaultOffset.clone().normalize().multiplyScalar(radius*3.8));controls.target.copy(target);controls.update();needsRender=true;}
 function focusParts(test){if(!model)return false;model.updateMatrixWorld(true);const box=new THREE.Box3();let count=0;model.traverseVisible(o=>{if(o.isMesh&&test(o.name,o)){box.expandByObject(o);count++;}});if(!count||box.isEmpty())return false;const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),detailRadius=Math.max(size.x,size.y,size.z,radius*.12)*.65;controls.minDistance=Math.min(radius*.75,detailRadius*.8);controls.target.copy(center);camera.position.copy(center).add(defaultOffset.clone().normalize().multiplyScalar(detailRadius*3.8));controls.update();needsRender=true;return true;}
 function resize(){const rect=canvas.parentElement.getBoundingClientRect();if(!rect.width||!rect.height)return;renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();needsRender=true;}
 const observer=new ResizeObserver(resize);observer.observe(canvas.parentElement);resize();
 async function load(path,options={}){
  if(destroyed||contextLost)throw new Error('Viewer unavailable');
  const token=++loadToken;
  if(path===loadedPath&&model){frameScale=options.fitScale||1;defaultOffset.set(...(options.cameraOffset||[.65,.55,1]));resetParts();fit();return model;}
  onStatus('正在下载三维物件…');if(model)model.visible=false;needsRender=true;
  let asset;
  try{asset=await loader.loadAsync(path,event=>{if(token!==loadToken||destroyed)return;const total=Number(event.total),loaded=Number(event.loaded);onStatus(total>0?'正在下载三维物件 · '+Math.round(Math.min(1,Math.max(0,loaded/total))*100)+'%':'正在下载三维物件…',total>0?Math.min(1,Math.max(0,loaded/total)):null);});}
  catch(error){if(token!==loadToken||destroyed)return null;throw error;}
  if(token!==loadToken||destroyed){disposeModel(asset.scene);return null;}
  if(model){scene.remove(model);disposeModel(model);}
  model=asset.scene;const table=model.getObjectByName('stage_wood');if(table){table.removeFromParent();disposeModel(table);}loadedPath=path;frameScale=options.fitScale||1;defaultOffset.set(...(options.cameraOffset||[.65,.55,1]));remember(model);scene.add(model);fit();resize();onStatus('');return model;
 }
 function projectPart(test){if(!model)return null;model.updateMatrixWorld(true);camera.updateMatrixWorld();let best=null,bestDistance=Infinity;model.traverseVisible(o=>{if(!o.isMesh||!test(o.name,o))return;const pos=o.geometry.attributes.position;if(!pos)return;const stride=Math.max(1,Math.floor(pos.count/64));for(let i=0;i<pos.count;i+=stride){const point=new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld),distance=point.distanceToSquared(camera.position);if(distance<bestDistance){bestDistance=distance;best=point;}}});if(!best)return null;const p=best.project(camera);return{x:(p.x+1)/2,y:(1-p.y)/2,visible:p.z>=-1&&p.z<=1};}
 function zoom(factor){const off=camera.position.clone().sub(controls.target);off.setLength(THREE.MathUtils.clamp(off.length()*factor,controls.minDistance,controls.maxDistance));camera.position.copy(controls.target).add(off);controls.update();needsRender=true;}
 function top(){camera.position.copy(controls.target).add(new THREE.Vector3(.0001,radius*3.8,.0001));controls.update();needsRender=true;}
 function onKey(e){if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const s=new THREE.Spherical().setFromVector3(camera.position.clone().sub(controls.target));s.theta+=e.key==='ArrowLeft'?.12:e.key==='ArrowRight'?-.12:0;s.phi=THREE.MathUtils.clamp(s.phi+(e.key==='ArrowUp'?-.12:e.key==='ArrowDown'?.12:0),.02,Math.PI*.85);camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(s));controls.update();needsRender=true;}else if(e.key==='+'||e.key==='=')zoom(.85);else if(e.key==='-')zoom(1.18);}
 function onLost(e){e.preventDefault();contextLost=true;active=false;loadToken++;onStatus('三维画面已暂停。可以重试，或先查看过程画面。',null,true);}
 canvas.addEventListener('keydown',onKey);canvas.addEventListener('webglcontextlost',onLost);
 function frame(){if(destroyed)return;rafId=requestAnimationFrame(frame);if(!active||document.hidden||contextLost)return;const changed=controls.update();if(changed||needsRender){renderer.render(scene,camera);needsRender=false;projectionHandler?.();}}frame();
 return{load,projectPart,setProjectionHandler(fn){projectionHandler=fn;needsRender=true;},cancelLoad(){loadToken++;if(model)model.visible=false;needsRender=true;},each,eachNode,resetParts,resetCamera,focusParts,zoom,top,get radius(){return radius;},get model(){return model;},get contextLost(){return contextLost;},setActive(value){if(destroyed)return;active=value;if(value)resize();},setColor(test,color){each(test,o=>(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.color?.set(color)));},dispose(){destroyed=true;projectionHandler=null;active=false;loadToken++;if(rafId!==null&&typeof cancelAnimationFrame==='function')cancelAnimationFrame(rafId);observer.disconnect();canvas.removeEventListener('keydown',onKey);canvas.removeEventListener('webglcontextlost',onLost);disposeModel(model);environment?.dispose();key.shadow.dispose?.();ground.geometry.dispose();ground.material.dispose();controls.dispose();renderer.dispose();}};
}
