/** Source-grounded explanations revealed on pause; no predicted process/taste values. */
export const mechanismData={
 cherry:{title:'果实里的六个名称',material:'从咖啡树采下的成熟红果；剖面和局部放大仅用于观察',action:'展开外果皮与果肉，观察通常两颗、平面相对的种子',inside:'果胶是果肉内侧的黏液质。羊皮层分别包着每颗种子；银皮是紧贴豆体的极薄膜。种子主体是胚乳，小胚未单独绘出',purpose:'认清后面每一步究竟去掉什么、留下什么',output:'仍然是鲜果里的种子，尚未水洗、干燥或烘焙',advanced:['六个名字不是六层独立硬壳；果胶也不是纯化学果胶。','观察窗、分离距离和薄层厚度被放大；种子没有在实际加工中被这样切开。','银皮的发生学术语在文献中存在差异，此处不把它再拆成另一层“种皮”。'],sources:[['NCA：咖啡果组织','https://www.aboutcoffee.org/origins/what-is-coffee/'],['FAO/Codex：黏液质与羊皮层','https://www.fao.org/input/download/standards/11250/CXP_069e.pdf'],['Geromel等：种子组织研究','https://academic.oup.com/jxb/article/57/12/3243/449464']]},
 depulp:{title:'去果肉，不是磨碎种子',material:'成熟鲜果；去果肉机的转动工作面和可调通道',action:'机器使柔软果皮、果肉与较坚实的种子分离；种子进入下一道处理',inside:'外侧果肉离开，黏液质仍附着在羊皮层外；内部种子应尽量保持完整',purpose:'去掉大量果肉，为后面的去果胶和干燥做准备',output:'带着羊皮层和黏液质的湿种子',advanced:['通道、进料和成熟度需要配合；间隙或转速不合适可能损伤豆子。','滚筒、盘式和其他去果肉设备结构不同。画面只选择一种通用接触原理，不是具体厂家CAD。'],sources:[['FAO：采收与处理','https://www.fao.org/4/ae939e/ae939e08.htm'],['Penagos：去果肉机校准与损伤原因','https://penagos.com/en/technical-support/']]},
 ferment:{title:'发酵，为什么让果胶容易洗掉',material:'去果肉后的湿种子；清洁的发酵容器',action:'在受管理的条件下放置，并检查黏液质何时容易被洗除；之后进入清洗',inside:'与微生物及酶活性有关的变化，使外侧黏液质更容易去除。这里不是把种子加热烘熟',purpose:'帮助去掉黏附外层，同时管理不希望出现的过度发酵',output:'黏液质可被洗除、羊皮层仍包着种子的湿咖啡',advanced:['这是所选的传统水洗路线；机械去果胶也可替代发酵步骤。','成熟度、温度、微生物、容器和氧气条件都会影响过程；不把一组小时数当成通用配方。','不同地区会安排不同的发酵、浸泡与清洗流程。日晒路线让整果参与干燥；蜜处理保留黏液质参与干燥，不是本片这条路线。'],sources:[['FAO/Codex：发酵与机械去果胶','https://www.fao.org/input/download/standards/11250/CXP_069e.pdf'],['FAO：Kenya水洗处理','https://www.fao.org/4/x6939e/X6939e11.htm'],['处理变化综述','https://pmc.ncbi.nlm.nih.gov/articles/PMC8620865/']]},
 washed:{title:'清洗带走黏液质，薄壳留下',material:'发酵后易洗除黏液质的湿咖啡；清水、清洗槽或水道',action:'用水和适当翻动清洗，带走已松解的黏液质',inside:'羊皮层仍在，不能把去果胶画成直接洗出裸露生豆',purpose:'清掉残留物，准备带壳干燥',output:'洗净的湿带壳豆',advanced:['流路和淡色斑点表示水与被带走的黏液质，不是实际分子尺寸。','需要管理清洁、用水和排水；不同水洗系统并不完全相同。'],sources:[['NCA：处理路线','https://www.aboutcoffee.org/beans/processes/'],['FAO：清洗水道与翻动','https://www.fao.org/4/x6939e/X6939e11.htm']]},
 dry:{title:'为什么要先带壳干燥',material:'洗净的湿带壳豆；干净的网床、晾晒面或受控干燥设备',action:'摊开并翻动，让空气带走水分；防止重新淋湿',inside:'不只是外壳颜色改变，种子内和外层中的水分也逐步减少',purpose:'让咖啡更适于储存和后续脱壳，减少不当干燥带来的损伤与变质风险',output:'仍带羊皮层的干咖啡',advanced:['厚度、空气条件、日晒或设备热量、翻动和环境湿度都重要。','所需天数与目标监测条件依工艺和环境而异；动画把等待压缩了。'],sources:[['FAO：干燥操作与风险','https://www.fao.org/4/ae939e/ae939e08.htm'],['FAO：网床与翻动','https://www.fao.org/4/x6939e/X6939e11.htm']]},
 hull:{title:'脱壳，只去掉干薄壳',material:'干燥后的带壳豆；脱壳机',action:'机械工作面使干燥羊皮层破开、脱离，并将壳与豆分开',inside:'里面的生豆保留下来，不应被磨碎；银皮可能仍有残留',purpose:'得到可分级、储存并送去烘焙的生豆',output:'青绿色的生咖啡豆',advanced:['机型、设定和豆子干燥状态会影响破损。画面是局部接触原理，不是完整工业机器。','脱壳与抛光不是完全相同的操作；不宣称所有银皮都必须去净。'],sources:[['FAO：机械脱壳','https://www.fao.org/4/ae939e/ae939e08.htm'],['Pinhalense：脱壳设备','https://pinhalense.com.br/en/machines/coffee/hullers']]},
 roast:{title:'热如何进入豆子，为什么还要冷却',material:'生豆；热源、滚筒与翻动叶片、空气系统、冷却盘',action:'装豆后持续翻动与供热；达到目标发展程度后排豆，搅拌并通风冷却',inside:'水分减少，褐变和香气相关反应发生；体积、裂隙和内部孔隙结构也变化，不能只看表面颜色',purpose:'形成适合冲煮的熟豆，并通过冷却结束持续发展的烘焙过程',output:'冷却后的熟咖啡豆',advanced:['滚筒与气流型设备传热方式和混合方式不同；这里展示滚筒式的一种通用原理。','供热、气流、装豆量、时间进程与生豆共同影响结果；没有通用于所有豆与机器的温度/分钟数。','微观研究观察到孔隙随烘焙改变，变化并非简单线性；本动画不从颜色预测风味。'],sources:[['PROBAT：滚筒、叶片与热空气','https://www.probat.com/products/machines/roasting/p60/'],['PROBAT：滚筒与冷却系统','https://www.probat.com/products/specialty-coffee/p-series/'],['Schenker等：烘焙与孔隙结构','https://ift.onlinelibrary.wiley.com/doi/10.1111/j.1365-2621.2000.tb16026.x']]},
 grind:{title:'豆子怎样在刀盘间逐级变小',material:'熟豆；内锥、外环及粗细不同的磨齿',action:'上部预碎，较小碎块继续进入下部更细的工作区，再从间隙排出',inside:'不是整豆消失、另一批粉出现。这里追踪一粒豆的多个后代碎块，破裂与轨迹是教学编排',purpose:'增大可与水接触的表面，并通过研磨粗细影响粉床阻力',output:'大小不完全一致的咖啡粉',advanced:['颗粒和间隙为观察放大，不是浓缩研磨的毫米标尺。','不是所有锥刀都内锥转、外环固定；例如Sette采用外环转动。','调整间隙会改变粒度分布；实际表现还受刀形、转速、磨损和豆子影响。'],sources:[['Baratza：粗齿、细齿与间隙','https://www.baratza.com/en-au/landing/product/shop-by-burr-type'],['Acaia：Sette结构例外','https://help.acaia.co/hc/en-us/articles/360034876752-Baratza-Sette-270Wi']]},
 espresso:{title:'水怎样穿过粉饼，把咖啡带出来',material:'压实的咖啡粉、滤篮和加压热水',action:'水进入相连的颗粒间孔隙；携带溶出物，穿过滤孔并汇入杯中',inside:'可溶成分从颗粒中进入水相。大部分固体仍留下，不能把整块咖啡粉画成融化掉',purpose:'把部分咖啡成分转移到水里，得到浓缩饮液',output:'杯中浓缩液与滤篮中保留的湿粉饼',advanced:['宏观流路不应画成所有水同时、等速地通过直管。蓝/棕色与小点是液体和溶质的示踪，不是分子照片。','研磨分布、填装、通道效应、压差、温度和停止接液时刻都可能改变结果。','滤篮是承托粉床的穿孔金属，不是阻拦所有细粉的理想膜。18g粉→36g饮液只是常见起点，不是注水量。'],sources:[['Vaca Guerra等2024：多孔粉床与溶质传输','https://tore.tuhh.de/entities/publication/313fb619-97a3-40fb-a075-9b8cfdec4af0/'],['IMS：滤篮穿孔结构','https://www.imsfiltri.com/IMS-competition-Catalogue.pdf'],['La Marzocco：粉液比','https://www.lamarzocco.com/uk/en/using-espresso-brew-ratios/']]},
 steam:{title:'牛奶怎样从进气到细腻融合',material:'牛奶、奶缸和蒸汽棒',action:'先让棒尖接近表面少量进气，再稍深一些形成流动；停汽后移开',inside:'空气分散进奶液，蒸汽同时传热；动作、奶种和设备会影响泡沫结构',purpose:'得到细腻且能流动的奶泡，而不是一堆干硬大泡',output:'可用于与浓缩融合、形成表面图案的热奶泡',advanced:['表面波纹是动作示意，未解算真实气泡分布、体积变化和热力学。','关注质地与温度，并遵循设备安全说明；不能仅凭动画外观判断真实温度。'],sources:[['La Marzocco：蒸汽打奶','https://www.lamarzocco.com/uk/en/steaming-milk-on-the-linea-mini/']]},
 pour:{title:'高位融合，低位成形',material:'杯中浓缩与细腻奶泡；有壶嘴的奶缸',action:'先高位注奶融合，再靠近液面让白色展开，最后提壶收细流',inside:'不同注奶高度、流量和动作影响表面图案；整杯牛奶与咖啡已经在混合',purpose:'完成饮品，并在杯面留下图案',output:'完成的拿铁',advanced:['奶流和纹理展开经过视觉编排；不是可任意转动的真实流体模拟。','杯型、基底、奶泡质地、倾角和流量都会影响结果。'],sources:[['La Marzocco：拉花动作','https://www.lamarzocco.com/uk/en/how-to-pour-latte-art/']]},
 finished:{title:'回看这杯咖啡来自哪里',material:'成熟咖啡果中的种子，后来加入的水和牛奶',action:'种子经历处理、烘焙和研磨，部分成分被水带入杯中，再加入牛奶',inside:'果肉与壳、杯中的饮液、滤篮中的粉渣，是不同步骤留下的不同部分',purpose:'把原料、工具、动作和结果联系起来',output:'一杯拿铁；能说清每一步的输入与输出',advanced:['少量代表性物料不等于实际一杯所需的果实或豆数。','想研究某一步，可暂停后旋转参考模型，展开变量和来源；熟悉流程时可关闭解说直接跳章节。'],sources:[['NCA：从果实到咖啡','https://www.aboutcoffee.org/origins/lifecycle-of-coffee/']]}
};
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mechanismContent(key){const m=mechanismData[key]||mechanismData.washed;return{...m,html:'<dl class="mechanism-facts">'+[['材料与工具',m.material],['怎么做',m.action],['里面怎样变',m.inside],['为什么这样做',m.purpose],['留下什么',m.output]].map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('')+'</dl><details class="advanced-mechanism"><summary>变量、设备差异与资料</summary><ul>'+m.advanced.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul><div class="source-links">'+m.sources.map(([name,url])=>'<a href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(name)+'</a>').join('')+'</div></details>'};}
